#!/bin/sh

# Get the absolute path of the repository root
REPO_ROOT="$(git rev-parse --show-toplevel)"

bash "$REPO_ROOT/build.sh"
git add "$REPO_ROOT/docs"
git add "$REPO_ROOT/assets"
git add "$REPO_ROOT/SPRIND.customasm"
