:- module(sem, [
    instr_info/2,
    mod_def/2,
    instr_operand/2,
    syntax_operands/2,
    all_modules/1,
    module_instrs/2,
    module_info/2
]).

:- use_module(library(clpfd)).
:- use_module(querilog_syntax).

:- discontiguous(instr_info/2).

mod_def(subtr{
    x: in, y: in,
    diff: out, signin: out(1), carryout: out(1)
}, (
    adder{
        x: ?x, y: ~(?y), carryin: #1,
        sum: ?diff, signin: ?signin, carryout: ?carryout
    }
)).

mod_def(lessthan{
    x: in, y: in, lessthan: out(1)
}, (
    subtr{
        x: ?x, y: ?y,
        diff: ?diff, signin: ?sin, carryout: ?cout
    };
    % "Internally, the overflow flag is usually generated by an exclusive or
    % of the internal carry into and out of the sign bit."
    ?overflow := ?sin xor ?cout;
    % "If the exclusive-or of the sign and overflow flags is 1, the
    % subtraction result was less than zero, otherwise the result was zero
    % or greater."
    ?sign := bit(?diff, #15);
    ?lessthan := ?overflow xor ?sign
)).

mod_def(b_push{ stack_in: in(N), stack_out: out(N), bit: in(1) },
    ?stack_out := (?stack_in << #1) and zxt(?bit)
).
%mod_def(b_push{ bit: in(1) },
%    $$ts <- ($$ts << $1) and zxt(?bit)
%).
mod_def(b_pop{ stack_in: in(N), stack_out: out(N), bit: out(1) },
    ?bit := ?stack_in\1;
    ?stack_out := (?stack_in >> #1)
).
%mod_def(b_pop{ bit: out(1) },
%    ?bit := $$ts\1;
%    $$ts <- (?stack_in >> #1)
%).

instr_info(lb, info{
    title: 'Load Byte',
    descr: 'Load a byte from memory into a register.',
    ex: ['lb w, [sp+12]'],
    syntax: { reg(r, ?rs), [reg(s, ?rd) + simm(?simm)] },
    sem: (
        ?ptr := (?rs + sxt(?simm));
        ?rd <- zxt(mem(?ptr))
    ),
    tags: [mem, load, byte],
    module: [base]
}).
instr_info(lw, info{
    title: 'Load Word',
    descr: 'Load a word from memory into a register.',
    ex: ['lw w, [sp+12]'],
    syntax: { reg(r, ?rs), [reg(s, ?rd) + simm(?simm)] },
    sem: (
        ?ptr := ((?rs + sxt(?simm)) and #(-2)\16);
        ?rd <- {mem(?ptr + #1), mem(?ptr)}
    ),
    tags: [mem, load, word],
    module: [base]
}).
instr_info(sb, info{
    title: 'Store Byte',
    descr: 'Store a byte from a register into memory.',
    ex: ['sb [sp-20], x'],
    syntax: { [reg(r, ?rd) + simm(?simm)], reg(s, ?rs) },
    sem: (
        ?ptr := ?rd + sxt(?simm);
        mem(?ptr) <- lo(?rs)
    ),
    tags: [mem, store, byte],
    module: [base]
}).
instr_info(sw, info{
    title: 'Store Word',
    descr: 'Store a word from a register into memory.',
    ex: ['sw [sp-20], x'],
    syntax: { [reg(r, ?rd) + simm(?simm)], reg(s, ?rs) },
    sem: (
        ?ptr := (?rd + sxt(?simm)) and ~(#1\16);
        mem(?ptr) <- lo(?rs);
        mem(?ptr + #1) <- hi(?rs)
    ),
    tags: [mem, store, word],
    module: [base]
}).

instr_info(call, info{
    title: 'Call Subroutine',
    descr: 'Call a subroutine at the specified address.',
    ex: ['call SOME_LABEL'],
    syntax: ({ simm(?arg) } -> (
        ?abs_lbl := ?arg;
        ?rel_lbl := ?abs_lbl - #asm_pc;
        { ?rel_lbl\size(imm) }
    )),
    sem: (
        ?offset := ?arg;
        $$pc <- $$pc + (sxt(?offset) << #subr_align);
        $$ra <- $$pc + #2
    ),
    tags: [pc, ra],
    module: [base]
}).

instr_info(b, info{
    title: 'Branch',
    descr: 'Branch to the specified address by adding the immediate offset to `$PC`.',
    ex: ['b SOME_LABEL'],
    syntax: ({ simm(?arg) } -> (
        ?abs_lbl := ?arg;
        ?rel_lbl := ?abs_lbl - #asm_pc;
        { ?rel_lbl\size(imm) }
    )),
    sem: (
        ?offset := ?arg;
        $$pc <- $$pc + sxt(?offset)
    ),
    tags: [pc],
    module: [base]
}).
instr_info(bt, info{
    title: 'Branch If True',
    descr: 'Branch to the specified address if the condition is true by adding the immediate offset to `$PC`.',
    ex: ['bt SOME_LABEL'],
    syntax: ({ simm(?arg) } -> (
        % To the assembler, the arg is an absolute address...
        ?abs_lbl := ?arg;
        ?rel_lbl := ?abs_lbl - #asm_pc;
        { ?rel_lbl\size(imm) }
    )),
    sem: (
        % ...but to the CPU decoding the instr, the arg is an offset.
        ?offset := ?arg;
        b_pop{ stack_in: $$ts, stack_out: ->($$ts), bit: ?tos };
        $$pc <- if(?tos, $$pc + sxt(?offset), $$pc)
    ),
    tags: [pc, cond],
    module: [base]
}).
instr_info(bf, info{
    title: 'Branch If False',
    descr: 'Branch to the specified address if the condition is false by adding the immediate offset to `$PC`.',
    ex: ['bf SOME_LABEL'],
    syntax: { simm(?arg) } -> (
        % To the assembler, the arg is an absolute address...
        ?abs_lbl := ?arg;
        ?rel_lbl := ?abs_lbl - #asm_pc;
        { ?rel_lbl\size(imm) }
    ),
    sem: (
        % ...but to the CPU decoding the instr, the arg is an offset.
        ?offset := ?arg;
        b_pop{ stack_in: $$ts, stack_out: ->($$ts), bit: ?tos };
        $$pc <- if(?tos, $$pc, $$pc + sxt(?offset))
    ),
    tags: [pc, cond],
    module: [base]
}).

instr_info(li, info{
    title: 'Load Immediate',
    descr: 'Load an immediate value into a register.',
    ex: ['li x, 123'],
    syntax: { reg(r, ?rd), simm(?simm) },
    sem: ?rd <- sxt(?simm),
    tags: [sxt, data],
    module: [base]
}).
instr_info(szi, info{
    title: 'Shift Zero-extended Immediate',
    descr: 'Left-shift a zero-extended immediate value into a register.',
    ex: ['szi x, 0xB3'],
    syntax: { reg(r, ?rd), imm(?imm) },
    sem: ?rd <- (?rd << #8) or zxt(?imm),
    tags: [zxt, data, shift],
    module: [base]
}).

instr_info(lgb, info{
    title: 'Load Global Byte',
    descr: 'Load a byte from a memory address offset from `$GP`.',
    ex: ['lgb x, [gp+8]'],
    syntax: { reg(r, ?rd), [reg(s, ?rs) + imm(?disp)] },
    sem: (
        ?ptr := $$gp + zxt(?disp);
        ?rd <- zxt(mem(?ptr))
    ),
    tags: [mem, load, global, byte],
    module: [globals]
}).
instr_info(lgw, info{
    title: 'Load Global Word',
    descr: 'Load a word from a memory address offset from `$GP`.',
    ex: ['lgw x, [gp+8]'],
    syntax: { reg(r, ?rd), [reg(s, ?rs) + imm(?disp)] },
    sem: (
        ?ptr := ($$gp + zxt(?disp)) and ~(#1);
        ?rd <- {mem(?ptr + #1), mem(?ptr)}
    ),
    tags: [mem, load, global, word],
    module: [globals]
}).
instr_info(sgb, info{
    title: 'Store Global Byte',
    descr: 'Store a byte into memory address offset from `$GP`.',
    ex: ['sgb [gp+8], x'],
    syntax: { [reg(r, ?rd) + imm(?disp)], reg(s, ?rs) },
    sem: (
        ?ptr := $$gp + zxt(?disp);
        mem(?ptr) <- lo(?rs)
    ),
    tags: [mem, store, global, byte],
    module: [globals]
}).
instr_info(sgw, info{
    title: 'Store Global Word',
    descr: 'Store a word into memory address offset from `$GP`.',
    ex: ['sgw [gp+8], x'],
    syntax: { [reg(r, ?rd) + imm(?disp)], reg(s, ?rs) },
    sem: (
        ?ptr := ($$gp + zxt(?disp)) and ~(#1);
        {mem(?ptr + #1), mem(?ptr)} <- ?rs
    ),
    tags: [mem, store, global, word],
    module: [globals]
}).
instr_info(tbit, info{
    title: 'Test Bit',
    descr: 'Test a specific bit in a register, modifying `$TS`.',
    ex: ['tbit 12, w'],
    syntax: { imm(?bit_idx), reg(r, ?rs) },
    sem: (
        ?shamt := ?bit_idx\4;
        ?bit := (?rs >> ?shamt) and #1;
        $$ts <- ($$ts << #1) or ?bit
    ),
    tags: [ts, bit, bitwise],
    module: [bittests]
}).
instr_info(cbit, info{
    title: 'Clear Bit',
    descr: 'Clear a specific bit in a register.',
    ex: ['cbit 9, v'],
    syntax: { imm(?bit_idx), reg(r, ?rd) },
    sem: (
        ?idx := ?bit_idx\4;
        ?mask := ~(#1 << ?idx);
        ?rd <- ?rd and ?mask
    ),
    tags: [bit, bitwise, clear],
    module: [bittests]
}).
instr_info(sbit, info{
    title: 'Set Bit',
    descr: 'Set a specific bit in a register.',
    ex: ['sbit 15, a'],
    syntax: { imm(?bit_idx), reg(r, ?rd) },
    sem: (
        ?idx := ?bit_idx\4;
        ?mask := ~(#1 << ?idx);
        ?rd <- ?rd or ?mask
    ),
    tags: [bit, bitwise, set],
    module: [bittests]
}).
instr_info(tli, info{
    title: 'Test Less-than Immediate',
    descr: 'Test if a register value is less than an immediate value via signed comparison.',
    ex: ['tli x, -5'],
    syntax: { reg(r, ?rs), simm(?simm) },
    sem: (
        lessthan{ x: ?rs, y: ?simm, lessthan: ?bit };
        b_push{ stack_in: $$ts, stack_out: ->($$ts), bit: ?bit }
    ),
    tags: [ts, cmp, inequality, signed, '<'],
    module: [imms]
}).
instr_info(tgi, info{
    title: 'Test Greater-than Immediate',
    descr: 'Test if a register value is greater than an immediate value via signed comparison.',
    ex: ['tgi x, -5'],
    syntax: { reg(r, ?rs), simm(?simm) },
    sem: (
        lessthan{ x: ?simm, y: ?rs, lessthan: ?bit };
        b_push{ stack_in: $$ts, stack_out: ->($$ts), bit: ?bit }
    ),
    tags: [ts, cmp, inequality, signed, '>'],
    module: [imms]
}).
instr_info(tgei, info{
    title: 'Test Greater-than or Equal Immediate',
    descr: 'Test if a register value is greater than or equal to an immediate value via signed comparison.',
    ex: ['tgei x, -5'],
    syntax: { reg(r, ?rs), simm(?simm) },
    sem: (
        lessthan{ x: ?rs, y: ?simm, lessthan: ?bit };
        b_push{ stack_in: $$ts, stack_out: ->($$ts), bit: ~(?bit) }
    ),
    tags: [ts, cmp, inequality, signed, '>='],
    module: [imms]
}).
instr_info(tlei, info{
    title: 'Test Less-than or Equal Immediate',
    descr: 'Test if a register value is less than or equal to an immediate value via signed comparison.',
    ex: ['tlei x, -5'],
    syntax: { reg(r, ?rs), simm(?simm) },
    sem: (
        lessthan{ x: ?simm, y: ?rs, lessthan: ?bit };
        b_push{ stack_in: $$ts, stack_out: ->($$ts), bit: ~(?bit) }
    ),
    tags: [ts, cmp, inequality, signed, '=<'],
    module: [imms]
}).
instr_info(tbi, info{
    title: 'Test Below Immediate',
    descr: 'Test if a register value is below an immediate value via unsigned comparison.',
    ex: ['tbi x, 10'],
    syntax: { reg(r, ?rs), imm(?imm) },
    sem: (
        todo
    ),
    tags: [ts, cmp, inequality, unsigned, '<'],
    module: [imms]
}).
instr_info(tai, info{
    title: 'Test Above Immediate',
    descr: 'Test if a register value is above an immediate value via unsigned comparison.',
    ex: ['tai x, 10'],
    syntax: { reg(r, ?rs), imm(?imm) },
    sem: (
        todo
    ),
    tags: [ts, cmp, inequality, unsigned, '>'],
    module: [imms]
}).
instr_info(taei, info{
    title: 'Test Above or Equal',
    descr: 'Test if a register value is above or equal to an immediate value via unsigned comparison.',
    ex: ['taei x, 10'],
    syntax: { reg(r, ?rs), imm(?imm) },
    sem: todo,
    tags: [ts, cmp, inequality, unsigned, '>='],
    module: [imms]
}).
instr_info(tbei, info{
    title: 'Test Below or Equal',
    descr: 'Test if a register value is below or equal to an immediate value via unsigned comparison.',
    ex: ['tbei x, 10'],
    syntax: { reg(r, ?rs), imm(?imm) },
    sem: todo,
    tags: [ts, cmp, inequality, unsigned, '=<'],
    module: [imms]
}).
instr_info(tnei, info{
    title: 'Test Not Equal Immediate',
    descr: 'Test if a register value is not equal to an immediate value.',
    ex: ['tnei x, 0'],
    syntax: { reg(r, ?rs), simm(?simm) },
    sem: b_push{ stack_in: $$ts, bit: ~(?rs == sxt(?simm)), stack_out: ->($$ts) },
    tags: [ts, cmp, equality, not],
    module: [imms]
}).
instr_info(teqi, info{
    title: 'Test Equal Immediate',
    descr: 'Test if a register value is equal to an immediate value.',
    ex: ['teqi x, -5'],
    syntax: { reg(r, ?rs), simm(?simm) },
    sem: b_push{ stack_in: $$ts, bit: ?rs == sxt(?simm), stack_out: ->($$ts) },
    tags: [ts, cmp, equality],
    module: [imms]
}).
instr_info(addi, info{
    title: 'Add Immediate',
    descr: 'Add an immediate value to a register.',
    ex: ['addi x, -5'],
    syntax: { reg(r, ?rd), simm(?simm) },
    sem: ?rd <- ?rd + sxt(?simm),
    tags: [arith],
    module: [imms]
}).
instr_info(andi, info{
    title: 'AND Immediate',
    descr: 'Perform a bitwise AND between a register and an immediate value.',
    ex: ['andi x, 3'],
    syntax: { reg(r, ?rd), simm(?simm) },
    sem: ?rd <- ?rd and sxt(?simm),
    tags: [logical, boolean, bitwise, and],
    module: [imms]
}).
instr_info(ori, info{
    title: 'OR Immediate',
    descr: 'Perform a bitwise OR between a register and an immediate value.',
    ex: ['ori x, 3'],
    syntax: { reg(r, ?rd), simm(?simm) },
    sem: ?rd <- ?rd or sxt(?simm),
    tags: [logical, boolean, bitwise],
    module: [imms]
}).

instr_info(xori, info{
    title: 'XOR Immediate',
    descr: 'Perform a bitwise XOR between a register and an immediate value.',
    ex: ['xori x, 3'],
    syntax: { reg(r, ?rd), simm(?simm) },
    sem: ?rd <- ?rd xor sxt(?simm),
    tags: [logical, boolean, bitwise, xor],
    module: [imms]
}).
instr_info(addicy, info{
    title: 'Add Immediate with Carry',
    descr: 'Add an immediate value and the carry bit to a register.',
    ex: ['addicy x, 3'],
    syntax: { reg(r, ?rd), simm(?simm) },
    sem: (
        adder{
            sum: ->(?rd), x: ?rd, y: sxt(?simm),
            carryin: bit($$cc, #cc::carry_flag_bit),
            carryout: ?cout, signin: ?sin
        };
        ?overflow := ?sin xor ?cout;
        bit($$cc, #cc::carry_flag_bit) <- ?cout;
        bit($$cc, #cc::overflow_flag_bit) <- ?overflow
    ),
    tags: [arith, carry, add],
    module: [imms]
}).
instr_info(subicy, info{
    title: 'Subtract Immediate with Carry',
    descr: 'Sutract an immediate value and the carry bit from a register.',
    ex: ['subicy x, 3'],
    syntax: { reg(r, ?rd), simm(?simm) },
    sem: todo(
        subtr{
            diff: ->(?rd), x: ?rd, y: ?simm
        };
        ?rd <- ?rd\s - sxt(?simm) - bit($$cc, #cc::carry_flag_bit)\16\s;
        bit($$cc, #cc::carry_flag_bit) <- attr(cpu/alu/carryout);
        bit($$cc, #cc::overflow_flag_bit) <- attr(cpu/alu/overflow)
    ),
    tags: [arith, carry],
    module: [imms]
}).
instr_info(lsr, info{
    title: 'Logical Shift Right',
    descr: 'Perform a logical shift right on a register by a 4-bit immediate value.',
    ex: ['lsr x, 15'],
    syntax: { reg(r, ?rd), imm(?imm) },
    sem: (
        bit($$cc, #cc::carry_flag_bit) <- bit(?rd, ?imm\4 - #1);
        ?rd <- ?rd >> ?imm\4
    ),
    tags: [bitwise, shift, right],
    module: [base]
}).
instr_info(lsl, info{
    title: 'Logical Shift Left',
    descr: 'Perform a logical shift left on a register by an immediate value.',
    ex: ['lsl x, 8'],
    syntax: { reg(r, ?rd), imm(?imm) },
    sem: (
        bit($$cc, #cc::carry_flag_bit) <- bit(?rd, (#reg_size_bits - ?imm)\4);
        ?rd <- ?rd << ?imm\4
    ),
    tags: [zxt, bitwise, shift, left],
    module: [base]
}).

instr_info(asr, info{
    title: 'Arithmetic Shift Right',
    descr: 'Perform an arithmetic shift right on a register by an immediate value.',
    ex: ['asr x, 3'],
    syntax: { reg(r, ?rd), imm(?imm) },
    sem: (
        ?sign := bit(?rd, (#reg_size_bits - #1)\4);
        ?sign_extension := (sxt(?sign - #1)) << (#reg_size_bits - ?imm)\4;
        bit($$cc, #cc::carry_flag_bit) <- bit(?rd, (?imm - #1)\4);
        ?rd <- (?rd >> ?imm\4) or ?sign_extension 
    ),
    tags: [sxt, bitwise, shift, right],
    module: [base]
}).
instr_info(tbitm, info{
    title: 'Test Bit in Memory',
    descr: '',
    ex: ['tbitm [x], 3'],
    syntax: { [reg(r, ?rs)], imm(?imm) },
    sem: b_push{ stack_in: $$ts, bit: bit(mem(?rs), ?imm\3), stack_out: ->($$ts) },
    tags: [ts, bit, bitwise, mem],
    module: [bittests]
}).
instr_info(cbitm, info{
    title: 'Clear Bit in Memory',
    descr: '',
    ex: ['cbitm [x], 3'],
    syntax: { [reg(r, ?rs)], imm(?imm) },
    sem: (
        mem(?rs) <- mem(?rs) and ~(#1 << ?imm\3)
    ),
    tags: [ts, bit, bitwise, clear, mem],
    module: [bittests]
}).
instr_info(sbitm, info{
    title: 'Set Bit in Memory',
    descr: '',
    ex: ['sbitm [x], 3'],
    syntax: { [reg(r, ?rs)], imm(?imm) },
    sem: (
        mem(?rs) <- mem(?rs) or (#1 << ?imm\3)
    ),
    tags: [ts, bit, bitwise, set, mem],
    module: [bittests]
}).

instr_info(add, info{
    title: 'Add',
    descr: 'Add the values of two registers.',
    ex: ['add x, y'],
    syntax: { reg(r, ?rd), reg(s, ?rs) },
    sem: adder{
        x: ?rd, y: ?rs, sum: ->(?rd),
        carryout: ->(bit($$cc, #cc::carry_flag_bit))
    },
    tags: [arith, add],
    module: [base]
}).
instr_info(sub, info{
    title: 'Subtract',
    descr: 'Subtract the value of one register from another.',
    ex: ['sub x, y'],
    syntax: { reg(r, ?rd), reg(s, ?rs) },
    sem: todo(?rd <- ?rd - ?rs),
    tags: [arith],
    module: [base]
}).
instr_info(and, info{
    title: 'AND',
    descr: 'Perform a bitwise AND between two registers.',
    ex: ['and x, y'],
    syntax: { reg(r, ?rd), reg(s, ?rs) },
    sem: ?rd <- ?rd and ?rs,
    tags: [logical, boolean, bitwise, and],
    module: [base]
}).
instr_info(or, info{
    title: 'OR',
    descr: 'Perform a bitwise OR between two registers.',
    ex: ['or x, y'],
    syntax: { reg(r, ?rd), reg(s, ?rs) },
    sem: ?rd <- ?rd or ?rs,
    tags: [logical, boolean, bitwise],
    module: [base]
}).
instr_info(xor, info{
    title: 'XOR',
    descr: 'Perform a bitwise XOR between two registers.',
    ex: ['xor x, y'],
    syntax: { reg(r, ?rd), reg(s, ?rs) },
    sem: ?rd <- ?rd xor ?rs,
    tags: [logical, boolean, bitwise, xor],
    module: [base]
}).
instr_info(mov, info{
    title: 'Move',
    descr: 'Move the value from one register to another.',
    ex: ['mov x, y'],
    syntax: { reg(r, ?rd), reg(s, ?rs) },
    sem: ?rd <- ?rs,
    tags: [data],
    module: [base]
}).
instr_info(addcy, info{
    title: 'Add with Carry',
    descr: 'Add the values of two registers with carry.',
    ex: ['addcy x, y'],
    syntax: { reg(r, ?rd), reg(s, ?rs) },
    sem: (
        adder{
            x: ?rd, y: ?rs, sum: ->(?rd),
            carryout: ?cout, signin: ?sin,
            carryin: bit($$cc, #cc::carry_flag_bit)
        };
        bit($$cc, #cc::carry_flag_bit) <- ?cout;
        bit($$cc, #cc::overflow_flag_bit) <- ?sin xor ?cout % SHOULD ERROR
    ),
    tags: [arith, carry, add],
    module: [base]
}).
instr_info(subcy, info{
    title: 'Subtract with Carry',
    descr: 'Subtract the value of one register from another with carry.',
    ex: ['subcy x, y'],
    syntax: { reg(r, ?rd), reg(s, ?rs) },
    sem: todo(
        ?rd <- ?rd - ?rs - bit($$cc, #cc::carry_flag_bit)\16;
        bit($$cc, #cc::carry_flag_bit) <- attr(cpu/alu/carryout);
        bit($$cc, #cc::overflow_flag_bit) <- attr(cpu/alu/overflow)
    ),
    tags: [arith, carry],
    module: [base]
}).
instr_info(tl, info{
    title: 'Test Less-than',
    descr: 'Test if the value of one register is less than another.',
    ex: ['tl x, y'],
    syntax: { reg(r, ?r1), reg(s, ?r2) },
    sem: todo(b_push($$ts, compare(?r1, <(s\16), ?r2))),
    tags: [ts, cmp, inequality, signed, '<'],
    module: [base]
}).
instr_info(tge, info{
    title: 'Test Greater-than or Equal',
    descr: 'Test if the value of one register is greater than or equal to another.',
    ex: ['tge x, y'],
    syntax: { reg(r, ?r1), reg(s, ?r2) },
    sem: todo(b_push($$ts, compare(?r1, >=(s\16), ?r2))),
    tags: [ts, cmp, inequality, signed, '>='],
    module: [base]
}).
instr_info(tb, info{
    title: 'Test Below',
    descr: 'Test if the value of one register is below another.',
    ex: ['tb x, y'],
    syntax: { reg(r, ?r1), reg(s, ?r2) },
    sem: todo(b_push($$ts, compare(?r1, <(u\16), ?r2))),
    tags: [ts, cmp, inequality, unsigned, '<'],
    module: [base]
}).
instr_info(tae, info{
    title: 'Test Above or Equal',
    descr: 'Test if the value of one register is above or equal to another.',
    ex: ['tae x, y'],
    syntax: { reg(r, ?r1), reg(s, ?r2) },
    sem: todo(b_push($$ts, compare(?r1, >=(u\16), ?r2))),
    tags: [ts, cmp, inequality, unsigned, '>='],
    module: [base]
}).
instr_info(tne, info{
    title: 'Test Not Equal',
    descr: 'Test if the value of one register is not equal to another.',
    ex: ['tne x, y'],
    syntax: { reg(r, ?r1), reg(s, ?r2) },
    sem: todo(b_push($$ts, ?r1 \= ?r2)),
    tags: [ts, cmp, equality, not],
    module: [base]
}).
instr_info(teq, info{
    title: 'Test Equal',
    descr: 'Test if the value of one register is equal to another.',
    ex: ['teq x, y'],
    syntax: { reg(r, ?r1), reg(s, ?r2) },
    sem: todo(b_push($$ts, ?r1 == ?r2)),
    tags: [ts, cmp, equality],
    module: [base]
}).

instr_info(mulstep, info{
    title: 'Unsigned Multiplication Step',
    descr: 'Computes one step in a full 16-bit by 16-bit unsigned multiplication.',
    ex: ['mulstep x:y, z'],
    syntax: { reg(t, ?multiplicand_hi):reg(s, ?multiplicand_lo), reg(r, ?multiplier) },
    sem: todo(
        todo
        %?mask := ~((?multiplier and #1) - #1);
        %?masked_lo := ?multiplicand_lo and ?mask;
        %?masked_hi := ?multiplicand_hi and ?mask;
        %lo($$mp) <- lo($$mp) + ?masked_lo;
        %hi($$mp) <- hi($$mp) + ?masked_hi + attr(cpu/alu/carryout);
        %?shift_cout := bit(?multiplicand_lo, (#reg_size_bits - #1));
        %?multiplicand_lo <- ?multiplicand_lo << #1;
        %?multiplicand_hi <- ?multiplicand_hi << #1 + ?shift_cout;
        %?multiplier <- ?multiplier >> #1
    ),
    tags: [arith, shift],
    module: [mul]
}).

instr_info(pushb, info{
    title: 'Push Byte',
    descr: 'Push a byte from a register onto the stack.',
    ex: ['pushb x'],
    syntax: { reg(r, ?rs) },
    sem: (
        ?new_sp := $sp - #1;
        mem(?new_sp) <- ?rs\8;
        $sp <- ?new_sp
    ),
    tags: [sp, push, byte],
    module: [stack]
}).
instr_info(pushw, info{
    title: 'Push Word',
    descr: 'Push a word from a register onto the stack.',
    ex: ['pushw x'],
    syntax: { reg(r, ?rs) },
    sem: todo,
    tags: [sp, push, word],
    module: [stack]
}).
instr_info(popb, info{
    title: 'Pop Byte',
    descr: 'Pop a byte from the stack into a register.',
    ex: ['popb x'],
    syntax: { reg(r, ?rd) },
    sem: todo,
    tags: [sp, pop, byte],
    module: [stack]
}).
instr_info(popw, info{
    title: 'Pop Word',
    descr: 'Pop a word from the stack into a register.',
    ex: ['popw x'],
    syntax: { reg(r, ?rd) },
    sem: todo,
    tags: [sp, pop, word],
    module: [stack]
}).
instr_info(callr, info{
    title: 'Call Register',
    descr: 'Call a subroutine at the address in a register.',
    ex: ['callr x'],
    syntax: { reg(r, ?abs_lbl) },
    sem: (
        $$pc <- ?abs_lbl;
        $$ra <- $$pc + #2
    ),
    tags: [pc, ra, jump, indirect],
    module: [base]
}).
instr_info(jr, info{
    title: 'Jump Register',
    descr: 'Jump to the address in a register.',
    ex: ['jr x'],
    syntax: { reg(r, ?abs_lbl) },
    sem: $$pc <- ?abs_lbl,
    tags: [pc, jump, indirect],
    module: [base]
}).
instr_info(neg, info{
    title: 'Negate',
    descr: 'Negate the value in a register.',
    ex: ['neg x'],
    syntax: { reg(r, ?rd) },
    sem: todo(?rd <- -(?rd)),
    tags: [arith],
    module: [imms]
}).
instr_info(seb, info{
    title: 'Sign Extend Byte',
    descr: 'Sign extend a byte in a register.',
    ex: ['seb x'],
    syntax: { reg(r, ?rd) },
    sem: ?rd <- sxt(?rd\8),
    tags: [arith, sxt],
    module: [base]
}).
instr_info('rd.mp.lo', info{
    title: 'Read $MP.lo',
    descr: 'Read the low word in the system `$MP` register into a general purpose register.',
    ex: ['rd.mp.lo x'],
    syntax: { reg(r, ?rd) },
    sem: ?rd <- lo($$mp),
    tags: [rd, data, mp, lo],
    module: [mul]
}).
instr_info('rd.mp.hi', info{
    title: 'Read $MP.hi',
    descr: 'Read the high word in the system `$MP` register into a general purpose register.',
    ex: ['rd.mp.hi x'],
    syntax: { reg(r, ?rd) },
    sem: ?rd <- hi($$mp),
    tags: [rd, data, mp, hi],
    module: [mul]
}).
instr_info('rd.gp', info{
    title: 'Read $GP',
    descr: 'Read the value of the system `$GP` register into a general purpose register.',
    ex: ['rd.gp x'],
    syntax: { reg(r, ?rd) },
    sem: ?rd <- $$gp,
    tags: [rd, data, gp],
    module: [globals]
}).
instr_info('wr.gp', info{
    title: 'Write $GP',
    descr: 'Write a value to the system `$GP` register from a general purpose register.',
    ex: ['wr.gp x'],
    syntax: { reg(r, ?rs) },
    sem: $$gp <- ?rs,
    tags: [wr, data, gp],
    module: [globals]
}).

instr_info('NONEXE0', info{
    title: 'Non-executable (0s Version)',
    descr: 'Triggers a "non-executable instruction" exception. The entire instruction is 16 `0`s.',
    ex: ['NONEXE0'],
    syntax: {},
    sem: $$pc <- #isr::nonexe0,
    tags: [], % Giving this no tags ensures it gets sorted into the 0-most branch of the optree.
    module: [base]
}).
instr_info('BREAK', info{
    title: 'Breakpoint',
    descr: 'Trigger a breakpoint.',
    ex: ['BREAK'],
    syntax: {},
    sem: $$pc <- #isr::break,
    tags: [exc, dbg],
    module: [dbg]
}).
instr_info('UNIMPL', info{
    title: 'Unimplemented',
    descr: 'Unimplemented instruction.',
    ex: ['UNIMPL'],
    syntax: {},
    sem: $$pc <- #isr::unimpl,
    tags: [exc, dbg],
    module: [dbg]
}).
instr_info(kret, info{
    title: 'Kernel Return',
    descr: 'Return from kernel mode.',
    ex: ['kret'],
    syntax: {},
    sem: $$pc <- $$kr,
    tags: [kernel, kr, pc, ret],
    module: [interrupts]
}).
instr_info(kcall, info{
    title: 'Kernel Call',
    descr: 'Call a kernel function. The function index must be stored in `v`.',
    ex: ['kcall'],
    syntax: {},
    sem: (
        $$kr <- $$pc + #2;
        $$pc <- $v;
        todo
    ),
    tags: [kernel, kr, pc, call],
    module: [interrupts]
}).
instr_info(ret, info{
    title: 'Return',
    descr: 'Return from a subroutine.',
    ex: ['ret'],
    syntax: {},
    sem: $$pc <- $$ra,
    tags: [pc, ra, ret],
    module: [base]
}).
instr_info(tov, info{
    title: 'Test Overflow',
    descr: 'Test for overflow.',
    ex: ['tov'],
    syntax: {},
    sem: b_push{
        stack_in: $$ts,
        bit: bit($$cc, #cc::overflow_flag_bit),
        stack_out: ->($$ts)
    },
    tags: [ts, cc, ov],
    module: [base]
}).
instr_info(tcy, info{
    title: 'Test Carry',
    descr: 'Test for carry.',
    ex: ['tcy'],
    syntax: {},
    sem: b_push{
        stack_in: $$ts,
        bit: bit($$cc, #cc::carry_flag_bit),
        stack_out: ->($$ts)
    },
    tags: [ts, cc, cy],
    module: [base]
}).
instr_info('clr.cy', info{
    title: 'Clear Carry',
    descr: 'Clear the carry flag.',
    ex: ['clr.cy'],
    syntax: {},
    sem: bit($$cc, #cc::carry_flag_bit) <- #0,
    tags: [wr, cy],
    module: [base]
}).
instr_info('set.cy', info{
    title: 'Set Carry',
    descr: 'Set the carry flag.',
    ex: ['set.cy'],
    syntax: {},
    sem: bit($$cc, #cc::carry_flag_bit) <- #1,
    tags: [wr, cy],
    module: [base]
}).
instr_info(tpush0, info{
    title: 'Teststack Push 0',
    descr: 'Push 0 onto the test stack.',
    ex: ['tpush0'],
    syntax: {},
    sem: b_push{ stack_in: $$ts, bit: #0, stack_out: ->($$ts) },
    tags: [ts, push],
    module: [tsops]
}).
instr_info(tpush1, info{
    title: 'Teststack Push 1',
    descr: 'Push 1 onto the test stack.',
    ex: ['tpush1'],
    syntax: {},
    sem: b_push{ stack_in: $$ts, bit: #1, stack_out: ->($$ts) },
    tags: [ts, push],
    module: [tsops]
}).
instr_info(tnot, info{
    title: 'Teststack NOT',
    descr: 'Perform a NOT operation on the test stack.',
    ex: ['tnot'],
    syntax: {},
    sem: (
        b_pop{ stack_in: $$ts, stack_out: ?ts1, bit: ?bit };
        b_push{ stack_in: ?ts1, bit: ~(?bit), stack_out: ->($$ts) }
    ),
    tags: [ts, boolean],
    module: [tsops]
}).
instr_info(tand, info{
    title: 'Teststack AND',
    descr: 'Perform an AND operation on the test stack.',
    ex: ['tand'],
    syntax: {},
    sem: (
        b_pop{ stack_in: $$ts, stack_out: ?ts1, bit: ?a };
        b_pop{ stack_in: ?ts1, stack_out: ?ts2, bit: ?b };
        b_push{ stack_in: ?ts2, bit: (?a and ?b), stack_out: ->($$ts) }
    ),
    tags: [ts, boolean],
    module: [tsops]
}).
instr_info(tor, info{
    title: 'Teststack OR',
    descr: 'Perform an OR operation on the test stack.',
    ex: ['tor'],
    syntax: {},
    sem: (
        b_pop{ stack_in: $$ts, stack_out: ?ts1, bit: ?a };
        b_pop{ stack_in: ?ts1, stack_out: ?ts2, bit: ?b };
        b_push{ stack_in: ?ts2, bit: (?a or ?b), stack_out: ->($$ts) }
    ),
    tags: [ts, boolean],
    module: [tsops]
}).
instr_info(tdup, info{
    title: 'Teststack Duplicate',
    descr: 'Duplicate the top value on the test stack.',
    ex: ['tdup'],
    syntax: {},
    sem: (
        b_push{ stack_in: $$ts, bit: $$ts\1, stack_out: ->($$ts) }
    ),
    tags: [ts, data],
    module: [tsops]
}).
instr_info('prsv.mp', info{
    title: 'Preserve $MP',
    descr: 'Preserve the value of the `$MP` register onto the stack.',
    ex: [],
    syntax: {},
    sem: todo,
    tags: [sp, prsv_rstr, prsv, mp],
    module: [mul]
}).
instr_info('rstr.mp', info{
    title: 'Restore $MP',
    descr: 'Restore the value of the `$MP` register from the stack.',
    ex: [],
    syntax: {},
    sem: todo,
    tags: [sp, prsv_rstr, rstr, mp],
    module: [mul]
}).
instr_info('prsv.ts', info{
    title: 'Preserve $TS',
    descr: 'Preserve the value of the `$TS` register onto the stack.',
    ex: [],
    syntax: {},
    sem: todo,
    tags: [sp, prsv_rstr, prsv, ts],
    module: [interrupts]
}).
instr_info('rstr.ts', info{
    title: 'Restore $TS',
    descr: 'Restore the value of the `$TS` register from the stack.',
    ex: [],
    syntax: {},
    sem: todo,
    tags: [sp, prsv_rstr, rstr, ts],
    module: [interrupts]
}).
instr_info('prsv.ra', info{
    title: 'Preserve $RA',
    descr: 'Preserve the value of the `$RA` register onto the stack.',
    ex: [],
    syntax: {},
    sem: todo,
    tags: [sp, prsv_rstr, prsv, ra],
    module: [interrupts]
}).
instr_info('rstr.ra', info{
    title: 'Restore $RA',
    descr: 'Restore the value of the `$RA` register from the stack.',
    ex: [],
    syntax: {},
    sem: todo,
    tags: [sp, prsv_rstr, rstr, ra],
    module: [interrupts]
}).
instr_info('prsv.gp', info{
    title: 'Preserve $GP',
    descr: 'Preserve the value of the `$GP` register onto the stack.',
    ex: [],
    syntax: {},
    sem: todo,
    tags: [sp, prsv_rstr, prsv, gp],
    module: [globals]
}).
instr_info('rstr.gp', info{
    title: 'Restore $GP',
    descr: 'Restore the value of the `$GP` register from the stack.',
    ex: [],
    syntax: {},
    sem: todo,
    tags: [sp, prsv_rstr, rstr, gp],
    module: [globals]
}).
instr_info('prsv.cc', info{
    title: 'Preserve $CC',
    descr: 'Preserve the value of the `$CC` register onto the stack.',
    ex: [],
    syntax: {},
    sem: todo,
    tags: [sp, prsv_rstr, prsv, cc],
    module: [interrupts]
}).
instr_info('rstr.cc', info{
    title: 'Restore $CC',
    descr: 'Restore the value of the `$CC` register from the stack.',
    ex: [],
    syntax: {},
    sem: todo,
    tags: [sp, prsv_rstr, rstr, cc],
    module: [interrupts]
}).
instr_info(sleep, info{
    title: 'Sleep',
    descr: 'Puts processor into low-power sleep mode.',
    ex: ['sleep'],
    syntax: {},
    sem: todo,
    tags: [cc, sleep, interrupts],
    module: [interrupts]
}).
instr_info(vijt, info{
    title: 'Valid Indirect Jump Target',
    descr: 'When `$CC.jt` is `1`, the `callr` and `jr` instructions must jump to one of these instructions or an exception is raised.',
    ex: [],
    syntax: {},
    sem: todo(
        if(bit($$cc, #jmp_tgt_validation_en_flag_bit),
            if(bit($$cc, #jmp_tgt_validation_req_flag_bit),
                bit($$cc, #jmp_tgt_validation_req_flag_bit) <- #0,
                exception('ILLINSTR')
            )
        )
    ),
    tags: [pc, indirect, jump, security],
    module: [security]
}).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

instr_operand(Instr, Operand) :-
    instr_info(Instr, Info),
    syntax_operands(Info.syntax, Operands),
    member(Operand, Operands).

syntax_operands({}, []).
syntax_operands({CommaList}, VarDecls) :-
    comma_list(CommaList, Operands),
    phrase(operand_vardecl(Operands), VarDecls).
syntax_operands(Lhs -> _Rhs, Operands) :- syntax_operands(Lhs, Operands).

operand_vardecl([]) --> !, [].
operand_vardecl([ [Inner] |Xs]) --> !,
    [Inner],
    operand_vardecl(Xs).
operand_vardecl([A:B|Xs]) --> !,
    [A, B],
    operand_vardecl(Xs).
operand_vardecl([X|Xs]) -->
    [X],
    operand_vardecl(Xs).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

all_modules(Modules) :-
    aggregate_all(set(M), (
        instr_info(_, Info),
        [M] = Info.module
    ), Modules).

module_instrs(Module, Instrs) :-
    bagof(I, instr_module(I, Module), Instrs).

instr_module(Instr, Module) :-
    instr_info(Instr, Info),
    [Module] = Info.module.


module_info(base, info{
    title: 'Base',
    descr: 'The minimal set of features needed for general computation.',
    deps: []
}).

module_info(globals, info{
    title: 'Globals',
    descr: 'Instructions related to the `$GP` global variable pointer register and gloal variables.',
    deps: [base]
}).

module_info(bittests, info{
    title: 'Bit Tests',
    descr: 'Instructions related to testing specific bits of a register or memory.',
    deps: [base]
}).

module_info(dbg, info{
    title: 'Debugging',
    descr: 'Instructions which communicate with a debugger.',
    deps: [base]
}).

module_info(imms, info{
    title: 'Immediates',
    descr: 'Instructions contain embedded (immediate) values. Generally duplicates of instructions which operate on registers.',
    deps: [base]
}).

module_info(interrupts, info{
    title: 'Interrupts',
    descr: 'Instructions for handling and operating during hardware/software interrupts.',
    deps: [base, stack]
}).

module_info(mul, info{
    title: 'Multiply',
    descr: 'Instructions related to integer multiplication.',
    deps: [base, stack]
}).

module_info(security, info{
    title: 'Security',
    descr: 'Instructions related to computer security.',
    deps: [base]
}).

module_info(stack, info{
    title: 'Stack',
    descr: 'Instructions for manipulating the subroutine stack.',
    deps: [base]
}).

module_info(tsops, info{
    title: 'Test-stack Operations',
    descr: 'Instructions for manipulating the test-stack (`$TS`).',
    deps: [base]
}).
